# Generated by Django 5.0 on 2023-12-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pais',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
