# Generated by Django 5.0 on 2023-12-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_app', '0002_pessoa_data_nascimento_pessoa_email_pessoa_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pais',
            field=models.CharField(max_length=150),
        ),
    ]
